kind: pipeline
type: docker
name: web-portfolio-v2

clone:
  disable: true

steps:
  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: vps_ip
      username:
        from_secret: ssh_user
      port:
        from_secret: ssh_port
      key:
        from_secret: ssh_private_key
      script:
        - cd ~/projects/web-portfolio-v2
        - git pull origin master
        - docker-compose down
        - docker-compose up -d --build
        - docker system prune -f

trigger:
  event:
    - push
  branch:
    - master