kind: pipeline
type: ssh
name: web-portfolio-v2

server:
  host: 
    from_secret: vps_ip
  username:
    from_secret: username
  port:
    from_secret: port
  key:
    from_secret: ssh_private_key

clone: 
  disable: true

steps:
  - name: pull
    commands:
      - cd ~/projects/web-portfolio-v2
      - git checkout master
      - git pull origin master

  - name: build
    commands:
      - echo "Start deploy"
      - cd ~/projects/web-portfolio-v2
      - docker-compose down
      - docker-compose up -d --build
      - docker system prune -f

trigger:
  event:
    - push
  branch:
    - master