/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number
  slug: string
  title: string
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        children?: {
          text: string
          children?: {
            [k: string]: string
          }[]
          [k: string]: string | any
        }[]
        fields: {
          upload: {
            [k: string]: string
          }
          [k: string]: string | any
        }
        [k: string]: any
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  excerpt?: string | null
  isPublished?: boolean | null
  updatedAt: string
  createdAt: string
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T
  title?: T
  content?: T
  excerpt?: T
  isPublished?: T
  updatedAt?: T
  createdAt?: T
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?:
    | (
        | 'abap'
        | 'apex'
        | 'azcli'
        | 'bat'
        | 'c'
        | 'clojure'
        | 'coffee'
        | 'cpp'
        | 'csharp'
        | 'csp'
        | 'css'
        | 'dart'
        | 'dockerfile'
        | 'fsharp'
        | 'go'
        | 'graphql'
        | 'handlebars'
        | 'html'
        | 'ini'
        | 'java'
        | 'javascript'
        | 'json'
        | 'julia'
        | 'kotlin'
        | 'less'
        | 'lua'
        | 'markdown'
        | 'msdax'
        | 'mysql'
        | 'objective-c'
        | 'pascal'
        | 'perl'
        | 'pgsql'
        | 'php'
        | 'plaintext'
        | 'postiats'
        | 'powerquery'
        | 'powershell'
        | 'pug'
        | 'python'
        | 'r'
        | 'razor'
        | 'redis'
        | 'redshift'
        | 'ruby'
        | 'rust'
        | 'sb'
        | 'scheme'
        | 'scss'
        | 'shell'
        | 'sol'
        | 'sql'
        | 'st'
        | 'swift'
        | 'tcl'
        | 'typescript'
        | 'vb'
        | 'xml'
        | 'yaml'
      )
    | null
  code?: string | null
  id?: string | null
  blockName?: string | null
  blockType: 'code-block'
}
