import ClientWrapper from './client-wrapper'
import { ScreenIndicator } from '@/components/signal-indicator'
import './globals.css'

import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import { cn } from '@/lib'

export const metadata = {
  title: 'Franz',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${GeistSans.variable} ${GeistMono.variable} overflow-hidden
    `}
    >
      <body className={cn('overflow-hidden bg-background font-sans transition-colors')}>
        <ClientWrapper>{children}</ClientWrapper>
        {process.env.NODE_ENV !== 'production' && <ScreenIndicator />}
      </body>
    </html>
  )
}
