"use client";
import { useState } from "react";
// import type { Metadata } from "next";
import { Fira_Code, Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import { ScreenIndicator } from "@/components/SignalIndicator";

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

import "./globals.css";
import { MenuList } from "@/components/menu";
import { Menu } from "lucide-react";

const FiraCode = Fira_Code({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Franz",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [selectedTheme, setSelectedTheme] = useState("light");

  return (
    <html lang="en">
      <body className={cn("bg-gray-200", inter.className)}>
        <div className="flex">
          <aside className="hidden w-[20vw] bg-gray-200 px-5 py-5 text-white md:block">
            <MenuList />
          </aside>

          <main className="mx-5 mt-5 w-full rounded-t-[30px] bg-white">
            <div className="m-5 block md:hidden">
              <Sheet>
                <SheetTrigger>
                  <Menu />
                </SheetTrigger>
                <SheetContent>
                  <MenuList />
                </SheetContent>
              </Sheet>
            </div>
            <div className="overflow-auto p-5">{children}</div>
          </main>
          {process.env.NODE_ENV !== "production" && <ScreenIndicator />}
        </div>
      </body>
    </html>
  );
}
